# .github/workflows/deploy.yml

# This workflow is designed to run in your forked documentation repository (kaerez/quickchart-docs).
# It checks out the corresponding website repository (kaerez/quickchart-site),
# updates its submodules, and pushes the changes back.

name: Send submodule updates to parent repo

on:
  push:
    branches:
      - main  # Corrected to use the 'main' branch

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the website repository (your fork) using a Personal Access Token
      - uses: actions/checkout@v4  # Updated to the latest version
        with:
          # IMPORTANT: This must point to YOUR forked repository
          repository: kaerez/quickchart-site
          # This uses the Personal Access Token you must create
          token: ${{ secrets.PRIVATE_TOKEN_GITHUB }}

      # Step 2: Update the submodules to their latest versions
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote

      # Step 3: Commit and push any changes back to your repository
      - name: Commit and Push Changes
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - update submodules"
          # Check if there are any changes to commit
          if [[ -n $(git status -s) ]]; then
            git add --all
            git commit -m "Update submodules to latest versions"
            git push
          else
            echo "No changes to commit."
          fi
